name = "oslira-api"
main = "src/index.ts"
compatibility_date = "2025-08-01"

# Production routes (your existing domain)
routes = [
  { pattern = "api.oslira.com/*", zone_name = "oslira.com" }
]

[vars]
APP_ENV = "production"

# Staging environment (completely separate)
[env.staging]
name = "oslira-api-stg"
workers_dev = true  # Uses workers.dev subdomain

[env.staging.vars]
APP_ENV = "staging"
