name = "ai-outreach-api"
account_id = "ec3a04af3fca5fbb10ec831616e63cfc"
workers_dev = true
compatibility_date = "2025-07-09"
main = "src/index.ts"  # Changed from index.ts to index.js

[vars]
SUPABASE_URL = "https://jswzzihuqtjqvobfosks.supabase.co"

