# Zero secrets, zero config - just infrastructure bindings
name = "ai-outreach-api"
main = "src/index.ts"
compatibility_date = "2025-08-01"

routes = [
  { pattern = "api.oslira.com/*", zone_name = "oslira.com" }
]

[[kv_namespaces]]
binding = "OSLIRA_KV"
id = "dd86f413c4374811ac253bb9a6567182"

[[r2_buckets]]
binding = "R2_CACHE_BUCKET"
bucket_name = "oslira-preprocessor-cache"

# Staging environment
[env.staging]
name = "oslira-api-stg"

routes = [
  { pattern = "api-staging.oslira.com/*", zone_name = "oslira.com" }
]

[[env.staging.kv_namespaces]]
binding = "OSLIRA_KV"
id = "dd86f413c4374811ac253bb9a6567182"

[[env.staging.r2_buckets]]
binding = "R2_CACHE_BUCKET"
bucket_name = "oslira-preprocessor-cache"
