name = "ai-outreach-api"
main = "src/index.ts"
compatibility_date = "2025-08-01"

routes = [
  { pattern = "api.oslira.com/*", zone_name = "oslira.com" }
]

[vars]
APP_ENV = "production"
FRONTEND_URL = "https://oslira.com"

kv_namespaces = [
  { binding = "OSLIRA_KV", id = "dd86f413c4374811ac253bb9a6567182" }
]

[env.staging]
name = "oslira-api-stg"
routes = [
  { pattern = "api-staging.oslira.com/*", zone_name = "oslira.com" }
]
kv_namespaces = [
  { binding = "OSLIRA_KV", id = "dd86f413c4374811ac253bb9a6567182" }
]
[env.staging.vars]
APP_ENV = "staging" 
FRONTEND_URL = "https://osliratest.netlify.app"

[[r2_buckets]]
binding = "R2_CACHE_BUCKET"
bucket_name = "oslira-preprocessor-cache"

[[env.staging.r2_buckets]]
binding = "R2_CACHE_BUCKET"
bucket_name = "oslira-preprocessor-cache"
