name = "oslira-api"
main = "src/index.ts"
compatibility_date = "2025-08-01"

routes = [
  { pattern = "api.oslira.com/*", zone_name = "oslira.com" }
]

[vars]
APP_ENV = "production"
SUPABASE_URL = "https://jswzzihuqtjqvobfosks.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impzd3p6aWh1cXRqcXZvYmZvc2tzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyNTc2NDQsImV4cCI6MjA2NzgzMzY0NH0.Cz909ngJHcBkxp1aeFUn-ZvCrKRFf3phtGlrBvTCvWg"

[env.staging]
name = "oslira-api-stg"
workers_dev = true

[env.staging.vars]
APP_ENV = "staging"
SUPABASE_URL = "https://jswzzihuqtjqvobfosks.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impzd3p6aWh1cXRqcXZvYmZvc2tzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyNTc2NDQsImV4cCI6MjA2NzgzMzY0NH0.Cz909ngJHcBkxp1aeFUn-ZvCrKRFf3phtGlrBvTCvWg"
