name: Deploy Cloudflare Worker

on:
  push:
    paths:
      - 'cloudflare-workers/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Publish to Cloudflare
        run: wrangler publish
        working-directory: cloudflare-workers
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
