name: Deploy Cloudflare Worker

on:
  push:
    paths:
      - 'cloudflare-workers/**'
    branches:
      - main
  workflow_dispatch: # Allow manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install -g wrangler
        
      - name: Check if wrangler.toml exists
        run: |
          if [ -f cloudflare-workers/wrangler.toml ]; then
            echo "✅ wrangler.toml found"
            cat cloudflare-workers/wrangler.toml
          else
            echo "❌ wrangler.toml NOT found"
            ls -la cloudflare-workers/
          fi
        
      - name: Authenticate with Cloudflare
        run: |
          echo "${{ secrets.CLOUDFLARE_API_TOKEN }}" | wrangler auth
        working-directory: cloudflare-workers
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          
      - name: Deploy Worker
        run: wrangler deploy
        working-directory: cloudflare-workers
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
